//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomechanicsProject.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutomechanicsProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя.
        /// </summary>
        public static string AuthLoginWatermark {
            get {
                return ResourceManager.GetString("AuthLoginWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите пароль.
        /// </summary>
        public static string AuthPasswordWatermark {
            get {
                return ResourceManager.GetString("AuthPasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название.
        /// </summary>
        public static string CategoryAddWatermark {
            get {
                return ResourceManager.GetString("CategoryAddWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите категорию.
        /// </summary>
        public static string CategorySelectWatermark {
            get {
                return ResourceManager.GetString("CategorySelectWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите артикул товара.
        /// </summary>
        public static string DeleteArticleWatermark {
            get {
                return ResourceManager.GetString("DeleteArticleWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Артикул.
        /// </summary>
        public static string EditArticleWatermark {
            get {
                return ResourceManager.GetString("EditArticleWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название.
        /// </summary>
        public static string EditCategoryWatermark {
            get {
                return ResourceManager.GetString("EditCategoryWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        public static string EditNameWatermark {
            get {
                return ResourceManager.GetString("EditNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена.
        /// </summary>
        public static string EditPriceWatermark {
            get {
                return ResourceManager.GetString("EditPriceWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Единица измерения.
        /// </summary>
        public static string EditUnitWatermark {
            get {
                return ResourceManager.GetString("EditUnitWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный логин или пароль!.
        /// </summary>
        public static string ErrorAuthInvalid {
            get {
                return ResourceManager.GetString("ErrorAuthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория с таким названием уже существует!.
        /// </summary>
        public static string ErrorCategoryExists {
            get {
                return ResourceManager.GetString("ErrorCategoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите артикул товара!.
        /// </summary>
        public static string ErrorEnterArticle {
            get {
                return ResourceManager.GetString("ErrorEnterArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите корректную цену!.
        /// </summary>
        public static string ErrorEnterCorrectPrice {
            get {
                return ResourceManager.GetString("ErrorEnterCorrectPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите корректное количество (целое положительное число)!.
        /// </summary>
        public static string ErrorEnterCorrectQuantity {
            get {
                return ResourceManager.GetString("ErrorEnterCorrectQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите количество товара!.
        /// </summary>
        public static string ErrorEnterQuantity {
            get {
                return ResourceManager.GetString("ErrorEnterQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите ФИО получателя!.
        /// </summary>
        public static string ErrorEnterRecipient {
            get {
                return ResourceManager.GetString("ErrorEnterRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название категории!.
        /// </summary>
        public static string ErrorFillCategory {
            get {
                return ResourceManager.GetString("ErrorFillCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заполните все обязательные поля!.
        /// </summary>
        public static string ErrorFillFields {
            get {
                return ResourceManager.GetString("ErrorFillFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недостаточно товара на складе!.
        /// </summary>
        public static string ErrorInsufficientStock {
            get {
                return ResourceManager.GetString("ErrorInsufficientStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароли не совпадают!.
        /// </summary>
        public static string ErrorPasswordMismatch {
            get {
                return ResourceManager.GetString("ErrorPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно удалить товар &quot;{0}&quot;, так как он используется в {1} отгрузках..
        /// </summary>
        public static string ErrorProductInShipments {
            get {
                return ResourceManager.GetString("ErrorProductInShipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар с артикулом &quot;{0}&quot; не найден!.
        /// </summary>
        public static string ErrorProductNotFound {
            get {
                return ResourceManager.GetString("ErrorProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите категорию!.
        /// </summary>
        public static string ErrorSelectCategory {
            get {
                return ResourceManager.GetString("ErrorSelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите категорию для удаления!.
        /// </summary>
        public static string ErrorSelectCategoryForDelete {
            get {
                return ResourceManager.GetString("ErrorSelectCategoryForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите товар из списка!.
        /// </summary>
        public static string ErrorSelectProduct {
            get {
                return ResourceManager.GetString("ErrorSelectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь с таким логином уже существует!.
        /// </summary>
        public static string ErrorUserExists {
            get {
                return ResourceManager.GetString("ErrorUserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите артикул.
        /// </summary>
        public static string ProductArticleWatermark {
            get {
                return ResourceManager.GetString("ProductArticleWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название.
        /// </summary>
        public static string ProductNameWatermark {
            get {
                return ResourceManager.GetString("ProductNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите цену.
        /// </summary>
        public static string ProductPriceWatermark {
            get {
                return ResourceManager.GetString("ProductPriceWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите единицы измерения.
        /// </summary>
        public static string ProductUnitWatermark {
            get {
                return ResourceManager.GetString("ProductUnitWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторите пароль.
        /// </summary>
        public static string RegConfirmPasswordWatermark {
            get {
                return ResourceManager.GetString("RegConfirmPasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите отчество.
        /// </summary>
        public static string RegLastnameWatermark {
            get {
                return ResourceManager.GetString("RegLastnameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите логин.
        /// </summary>
        public static string RegLoginWatermark {
            get {
                return ResourceManager.GetString("RegLoginWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя.
        /// </summary>
        public static string RegNameWatermark {
            get {
                return ResourceManager.GetString("RegNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите пароль.
        /// </summary>
        public static string RegPasswordWatermark {
            get {
                return ResourceManager.GetString("RegPasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите фамилию.
        /// </summary>
        public static string RegSurnameWatermark {
            get {
                return ResourceManager.GetString("RegSurnameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск:.
        /// </summary>
        public static string SearchWatermark {
            get {
                return ResourceManager.GetString("SearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите количество товара.
        /// </summary>
        public static string ShipmentQuantityWatermark {
            get {
                return ResourceManager.GetString("ShipmentQuantityWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите кому.
        /// </summary>
        public static string ShipmentRecipientWatermark {
            get {
                return ResourceManager.GetString("ShipmentRecipientWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория &quot;{0}&quot; успешно добавлена!.
        /// </summary>
        public static string SuccessCategoryAdded {
            get {
                return ResourceManager.GetString("SuccessCategoryAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория &quot;{0}&quot; успешно удалена!.
        /// </summary>
        public static string SuccessCategoryDeleted {
            get {
                return ResourceManager.GetString("SuccessCategoryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория &quot;{0}&quot; успешно переименована в &quot;{1}&quot;!.
        /// </summary>
        public static string SuccessCategoryUpdated {
            get {
                return ResourceManager.GetString("SuccessCategoryUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар успешно добавлен!.
        /// </summary>
        public static string SuccessProductAdded {
            get {
                return ResourceManager.GetString("SuccessProductAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар успешно удален!.
        /// </summary>
        public static string SuccessProductDeleted {
            get {
                return ResourceManager.GetString("SuccessProductDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар успешно обновлен!.
        /// </summary>
        public static string SuccessProductUpdated {
            get {
                return ResourceManager.GetString("SuccessProductUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация успешна! Добро пожаловать, {0}!.
        /// </summary>
        public static string SuccessRegistration {
            get {
                return ResourceManager.GetString("SuccessRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отгрузка успешно оформлена!.
        /// </summary>
        public static string SuccessShipmentCreated {
            get {
                return ResourceManager.GetString("SuccessShipmentCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение.
        /// </summary>
        public static string TitleConfirmation {
            get {
                return ResourceManager.GetString("TitleConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        public static string TitleInformation {
            get {
                return ResourceManager.GetString("TitleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успех.
        /// </summary>
        public static string TitleSuccess {
            get {
                return ResourceManager.GetString("TitleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание.
        /// </summary>
        public static string TitleWarning {
            get {
                return ResourceManager.GetString("TitleWarning", resourceCulture);
            }
        }
    }
}
