//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomechanicsProject.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutomechanicsProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя.
        /// </summary>
        public static string AuthLoginWatermark {
            get {
                return ResourceManager.GetString("AuthLoginWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите пароль.
        /// </summary>
        public static string AuthPasswordWatermark {
            get {
                return ResourceManager.GetString("AuthPasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название.
        /// </summary>
        public static string CategoryAddWatermark {
            get {
                return ResourceManager.GetString("CategoryAddWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Без категории.
        /// </summary>
        public static string CategoryNone {
            get {
                return ResourceManager.GetString("CategoryNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите категорию.
        /// </summary>
        public static string CategorySelectWatermark {
            get {
                return ResourceManager.GetString("CategorySelectWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите отменить добавление товара?
        ///Все введенные данные будут потеряны..
        /// </summary>
        public static string ConfirmCancelAddProduct {
            get {
                return ResourceManager.GetString("ConfirmCancelAddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите отменить удаление?.
        /// </summary>
        public static string ConfirmCancelDelete {
            get {
                return ResourceManager.GetString("ConfirmCancelDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас есть несохраненные изменения.
        ///Вы действительно хотите отменить редактирование?.
        /// </summary>
        public static string ConfirmCancelEdit {
            get {
                return ResourceManager.GetString("ConfirmCancelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас есть несохраненные изменения.
        ///
        ///Вы действительно хотите отменить редактирование?.
        /// </summary>
        public static string ConfirmCancelEditWithDetails {
            get {
                return ResourceManager.GetString("ConfirmCancelEditWithDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас есть добавленные товары в списке отгрузки.
        ///Вы действительно хотите отменить создание отгрузки?.
        /// </summary>
        public static string ConfirmCancelShipment {
            get {
                return ResourceManager.GetString("ConfirmCancelShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить категорию &quot;{0}&quot;?.
        /// </summary>
        public static string ConfirmDeleteCategory {
            get {
                return ResourceManager.GetString("ConfirmDeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В категории &quot;{0}&quot; находится {1} товаров.
        ///
        ///Вы уверены, что хотите удалить категорию и все товары в ней?
        ///Это действие нельзя отменить.
        /// </summary>
        public static string ConfirmDeleteCategoryWithProducts {
            get {
                return ResourceManager.GetString("ConfirmDeleteCategoryWithProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить товар?
        ///
        ///Артикул: {0}
        ///Название: {1}
        ///Категория: {2}
        ///Цена: {3:F2}
        ///Остаток: {4} {5}
        ///
        ///Это действие нельзя отменить!.
        /// </summary>
        public static string ConfirmDeleteProduct {
            get {
                return ResourceManager.GetString("ConfirmDeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить товар &quot;{0}&quot; из списка отгрузки?.
        /// </summary>
        public static string ConfirmRemoveShipmentItem {
            get {
                return ResourceManager.GetString("ConfirmRemoveShipmentItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердить отгрузку?
        ///
        ///Получатель: {0}
        ///Количество позиций: {1}
        ///Общая сумма: {2:C2}.
        /// </summary>
        public static string ConfirmShipment {
            get {
                return ResourceManager.GetString("ConfirmShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите артикул товара.
        /// </summary>
        public static string DeleteArticleWatermark {
            get {
                return ResourceManager.GetString("DeleteArticleWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Артикул.
        /// </summary>
        public static string EditArticleWatermark {
            get {
                return ResourceManager.GetString("EditArticleWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название.
        /// </summary>
        public static string EditCategoryWatermark {
            get {
                return ResourceManager.GetString("EditCategoryWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        public static string EditNameWatermark {
            get {
                return ResourceManager.GetString("EditNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена.
        /// </summary>
        public static string EditPriceWatermark {
            get {
                return ResourceManager.GetString("EditPriceWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Единица измерения.
        /// </summary>
        public static string EditUnitWatermark {
            get {
                return ResourceManager.GetString("EditUnitWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось добавить категорию. Попробуйте позже..
        /// </summary>
        public static string ErrorAddCategory {
            get {
                return ResourceManager.GetString("ErrorAddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при добавлении товара.
        /// </summary>
        public static string ErrorAddProduct {
            get {
                return ResourceManager.GetString("ErrorAddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при входе в систему.
        /// </summary>
        public static string ErrorAuthFailed {
            get {
                return ResourceManager.GetString("ErrorAuthFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный логин или пароль!.
        /// </summary>
        public static string ErrorAuthInvalid {
            get {
                return ResourceManager.GetString("ErrorAuthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно удалить категорию, так как некоторые товары используются в отгрузках.
        ///Сначала удалите связанные отгрузки..
        /// </summary>
        public static string ErrorCannotDeleteCategoryWithShipments {
            get {
                return ResourceManager.GetString("ErrorCannotDeleteCategoryWithShipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение категории товара запрещено!.
        /// </summary>
        public static string ErrorCategoryChangeForbidden {
            get {
                return ResourceManager.GetString("ErrorCategoryChangeForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Если вам необходимо изменить категорию, удалите товар и создайте новый в нужной категории..
        /// </summary>
        public static string ErrorCategoryChangeInstruction {
            get {
                return ResourceManager.GetString("ErrorCategoryChangeInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория с таким названием уже существует!.
        /// </summary>
        public static string ErrorCategoryExists {
            get {
                return ResourceManager.GetString("ErrorCategoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория не найдена в базе данных!.
        /// </summary>
        public static string ErrorCategoryNotFound {
            get {
                return ResourceManager.GetString("ErrorCategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердите пароль.
        /// </summary>
        public static string ErrorConfirmPassword {
            get {
                return ResourceManager.GetString("ErrorConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось оформить отгрузку.
        ///
        ///Ошибка: {0}.
        /// </summary>
        public static string ErrorCreateShipment {
            get {
                return ResourceManager.GetString("ErrorCreateShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось удалить категорию. Попробуйте позже..
        /// </summary>
        public static string ErrorDeleteCategory {
            get {
                return ResourceManager.GetString("ErrorDeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось удалить товар. Попробуйте позже..
        /// </summary>
        public static string ErrorDeleteProduct {
            get {
                return ResourceManager.GetString("ErrorDeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось отредактировать категорию. Попробуйте позже..
        /// </summary>
        public static string ErrorEditCategory {
            get {
                return ResourceManager.GetString("ErrorEditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при редактировании товара.
        /// </summary>
        public static string ErrorEditProduct {
            get {
                return ResourceManager.GetString("ErrorEditProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите артикул товара!.
        /// </summary>
        public static string ErrorEnterArticle {
            get {
                return ResourceManager.GetString("ErrorEnterArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите корректную цену!.
        /// </summary>
        public static string ErrorEnterCorrectPrice {
            get {
                return ResourceManager.GetString("ErrorEnterCorrectPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите корректное количество (целое положительное число)!.
        /// </summary>
        public static string ErrorEnterCorrectQuantity {
            get {
                return ResourceManager.GetString("ErrorEnterCorrectQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите логин.
        /// </summary>
        public static string ErrorEnterLogin {
            get {
                return ResourceManager.GetString("ErrorEnterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя.
        /// </summary>
        public static string ErrorEnterName {
            get {
                return ResourceManager.GetString("ErrorEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите пароль.
        /// </summary>
        public static string ErrorEnterPassword {
            get {
                return ResourceManager.GetString("ErrorEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите количество товара!.
        /// </summary>
        public static string ErrorEnterQuantity {
            get {
                return ResourceManager.GetString("ErrorEnterQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите ФИО получателя!.
        /// </summary>
        public static string ErrorEnterRecipient {
            get {
                return ResourceManager.GetString("ErrorEnterRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите фамилию.
        /// </summary>
        public static string ErrorEnterSurname {
            get {
                return ResourceManager.GetString("ErrorEnterSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название категории!.
        /// </summary>
        public static string ErrorFillCategory {
            get {
                return ResourceManager.GetString("ErrorFillCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заполните все обязательные поля!.
        /// </summary>
        public static string ErrorFillFields {
            get {
                return ResourceManager.GetString("ErrorFillFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, исправьте ошибки в форме.
        ///Поля, выделенные розовым, заполнены неверно..
        /// </summary>
        public static string ErrorFixFormErrors {
            get {
                return ResourceManager.GetString("ErrorFixFormErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка. Попробуйте позже..
        /// </summary>
        public static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недостаточно товара на складе!.
        /// </summary>
        public static string ErrorInsufficientStock {
            get {
                return ResourceManager.GetString("ErrorInsufficientStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недостаточно товара на складе!
        ///Доступно: {0} {1}.
        /// </summary>
        public static string ErrorInsufficientStockWithDetails {
            get {
                return ResourceManager.GetString("ErrorInsufficientStockWithDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчество должно содержать только русские буквы, дефис и пробел.
        /// </summary>
        public static string ErrorInvalidLastname {
            get {
                return ResourceManager.GetString("ErrorInvalidLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин может содержать только английские буквы, цифры и подчеркивание.
        /// </summary>
        public static string ErrorInvalidLogin {
            get {
                return ResourceManager.GetString("ErrorInvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя должно содержать только русские буквы, дефис и пробел.
        /// </summary>
        public static string ErrorInvalidName {
            get {
                return ResourceManager.GetString("ErrorInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль должен содержать минимум 6 символов, хотя бы одну цифру и одну букву.
        /// </summary>
        public static string ErrorInvalidPassword {
            get {
                return ResourceManager.GetString("ErrorInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия должна содержать только русские буквы, дефис и пробел.
        /// </summary>
        public static string ErrorInvalidSurname {
            get {
                return ResourceManager.GetString("ErrorInvalidSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчество должно быть от 2 до 100 символов.
        /// </summary>
        public static string ErrorLastnameLength {
            get {
                return ResourceManager.GetString("ErrorLastnameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось загрузить категории.
        /// </summary>
        public static string ErrorLoadCategories {
            get {
                return ResourceManager.GetString("ErrorLoadCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось загрузить товар.
        /// </summary>
        public static string ErrorLoadProduct {
            get {
                return ResourceManager.GetString("ErrorLoadProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось загрузить данные товара.
        /// </summary>
        public static string ErrorLoadProductData {
            get {
                return ResourceManager.GetString("ErrorLoadProductData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось загрузить товары.
        /// </summary>
        public static string ErrorLoadProducts {
            get {
                return ResourceManager.GetString("ErrorLoadProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось загрузить список товаров. Попробуйте позже..
        /// </summary>
        public static string ErrorLoadProductsList {
            get {
                return ResourceManager.GetString("ErrorLoadProductsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось загрузить список получателей.
        /// </summary>
        public static string ErrorLoadRecipients {
            get {
                return ResourceManager.GetString("ErrorLoadRecipients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось загрузить историю отгрузок: {0}.
        /// </summary>
        public static string ErrorLoadShipmentHistory {
            get {
                return ResourceManager.GetString("ErrorLoadShipmentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин должен быть от 3 до 20 символов.
        /// </summary>
        public static string ErrorLoginLength {
            get {
                return ResourceManager.GetString("ErrorLoginLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя должно быть от 2 до 100 символов.
        /// </summary>
        public static string ErrorNameLength {
            get {
                return ResourceManager.GetString("ErrorNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас нет доступа к системе! Обратитесь к администратору..
        /// </summary>
        public static string ErrorNoAccess {
            get {
                return ResourceManager.GetString("ErrorNoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавьте товары в список отгрузки!.
        /// </summary>
        public static string ErrorNoItemsInShipment {
            get {
                return ResourceManager.GetString("ErrorNoItemsInShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось открыть форму добавления категории.
        /// </summary>
        public static string ErrorOpenAddCategoryForm {
            get {
                return ResourceManager.GetString("ErrorOpenAddCategoryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось открыть форму добавления товара.
        /// </summary>
        public static string ErrorOpenAddProductForm {
            get {
                return ResourceManager.GetString("ErrorOpenAddProductForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось удалить категорию.
        /// </summary>
        public static string ErrorOpenDeleteCategoryForm {
            get {
                return ResourceManager.GetString("ErrorOpenDeleteCategoryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось открыть форму редактирования категории.
        /// </summary>
        public static string ErrorOpenEditCategoryForm {
            get {
                return ResourceManager.GetString("ErrorOpenEditCategoryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось открыть историю.
        /// </summary>
        public static string ErrorOpenHistory {
            get {
                return ResourceManager.GetString("ErrorOpenHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось открыть форму отгрузки.
        /// </summary>
        public static string ErrorOpenShipmentForm {
            get {
                return ResourceManager.GetString("ErrorOpenShipmentForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароли не совпадают!.
        /// </summary>
        public static string ErrorPasswordMismatch {
            get {
                return ResourceManager.GetString("ErrorPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно удалить товар &quot;{0}&quot;, так как он используется в {1} отгрузках..
        /// </summary>
        public static string ErrorProductInShipments {
            get {
                return ResourceManager.GetString("ErrorProductInShipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар с артикулом &quot;{0}&quot; не найден!.
        /// </summary>
        public static string ErrorProductNotFound {
            get {
                return ResourceManager.GetString("ErrorProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар не найден!.
        /// </summary>
        public static string ErrorProductNotFoundGeneric {
            get {
                return ResourceManager.GetString("ErrorProductNotFoundGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при регистрации. Попробуйте позже..
        /// </summary>
        public static string ErrorRegistration {
            get {
                return ResourceManager.GetString("ErrorRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка: роль &apos;Кладовщик&apos; не найдена!
        ///Обратитесь к администратору..
        /// </summary>
        public static string ErrorRoleNotFound {
            get {
                return ResourceManager.GetString("ErrorRoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите категорию!.
        /// </summary>
        public static string ErrorSelectCategory {
            get {
                return ResourceManager.GetString("ErrorSelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите категорию для удаления!.
        /// </summary>
        public static string ErrorSelectCategoryForDelete {
            get {
                return ResourceManager.GetString("ErrorSelectCategoryForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите товар из списка!.
        /// </summary>
        public static string ErrorSelectProduct {
            get {
                return ResourceManager.GetString("ErrorSelectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите получателя из списка!.
        /// </summary>
        public static string ErrorSelectRecipient {
            get {
                return ResourceManager.GetString("ErrorSelectRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия должна быть от 2 до 100 символов.
        /// </summary>
        public static string ErrorSurnameLength {
            get {
                return ResourceManager.GetString("ErrorSurnameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось обновить товар. Попробуйте позже..
        /// </summary>
        public static string ErrorUpdateProduct {
            get {
                return ResourceManager.GetString("ErrorUpdateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь с таким логином уже существует!.
        /// </summary>
        public static string ErrorUserExists {
            get {
                return ResourceManager.GetString("ErrorUserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название категории не изменилось.
        /// </summary>
        public static string InfoCategoryNameNotChanged {
            get {
                return ResourceManager.GetString("InfoCategoryNameNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на История отгрузок пуста.
        /// </summary>
        public static string InfoHistoryEmpty {
            get {
                return ResourceManager.GetString("InfoHistoryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет товаров в наличии для отгрузки!.
        /// </summary>
        public static string InfoNoProductsForShipment {
            get {
                return ResourceManager.GetString("InfoNoProductsForShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет доступных получателей!
        ///Обратитесь к администратору для добавления компаний..
        /// </summary>
        public static string InfoNoRecipientsAvailable {
            get {
                return ResourceManager.GetString("InfoNoRecipientsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет доступных категорий для удаления.
        /// </summary>
        public static string NoCategoriesForDelete {
            get {
                return ResourceManager.GetString("NoCategoriesForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар &quot;{0}&quot; уже добавлен в список.
        ///Текущее количество: {1} {2}
        ///
        ///Заменить количество новым значением?.
        /// </summary>
        public static string ProductAlreadyInList {
            get {
                return ResourceManager.GetString("ProductAlreadyInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите артикул.
        /// </summary>
        public static string ProductArticleWatermark {
            get {
                return ResourceManager.GetString("ProductArticleWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название.
        /// </summary>
        public static string ProductNameWatermark {
            get {
                return ResourceManager.GetString("ProductNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите цену.
        /// </summary>
        public static string ProductPriceWatermark {
            get {
                return ResourceManager.GetString("ProductPriceWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите единицы измерения.
        /// </summary>
        public static string ProductUnitWatermark {
            get {
                return ResourceManager.GetString("ProductUnitWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторите пароль.
        /// </summary>
        public static string RegConfirmPasswordWatermark {
            get {
                return ResourceManager.GetString("RegConfirmPasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите отчество.
        /// </summary>
        public static string RegLastnameWatermark {
            get {
                return ResourceManager.GetString("RegLastnameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите логин.
        /// </summary>
        public static string RegLoginWatermark {
            get {
                return ResourceManager.GetString("RegLoginWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя.
        /// </summary>
        public static string RegNameWatermark {
            get {
                return ResourceManager.GetString("RegNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите пароль.
        /// </summary>
        public static string RegPasswordWatermark {
            get {
                return ResourceManager.GetString("RegPasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите фамилию.
        /// </summary>
        public static string RegSurnameWatermark {
            get {
                return ResourceManager.GetString("RegSurnameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск:.
        /// </summary>
        public static string SearchWatermark {
            get {
                return ResourceManager.GetString("SearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите категорию для удаления.
        /// </summary>
        public static string SelectCategoryForDelete {
            get {
                return ResourceManager.GetString("SelectCategoryForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите категорию для редактирования.
        /// </summary>
        public static string SelectCategoryForEdit {
            get {
                return ResourceManager.GetString("SelectCategoryForEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите товар для удаления.
        /// </summary>
        public static string SelectProductForDelete {
            get {
                return ResourceManager.GetString("SelectProductForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите товар для редактирования.
        /// </summary>
        public static string SelectProductForEdit {
            get {
                return ResourceManager.GetString("SelectProductForEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите количество товара.
        /// </summary>
        public static string ShipmentQuantityWatermark {
            get {
                return ResourceManager.GetString("ShipmentQuantityWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите кому.
        /// </summary>
        public static string ShipmentRecipientWatermark {
            get {
                return ResourceManager.GetString("ShipmentRecipientWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория &quot;{0}&quot; успешно добавлена!.
        /// </summary>
        public static string SuccessCategoryAdded {
            get {
                return ResourceManager.GetString("SuccessCategoryAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория &quot;{0}&quot; и все ({1}) товары в ней успешно удалены!.
        /// </summary>
        public static string SuccessCategoryAndProductsDeleted {
            get {
                return ResourceManager.GetString("SuccessCategoryAndProductsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория &quot;{0}&quot; успешно удалена!.
        /// </summary>
        public static string SuccessCategoryDeleted {
            get {
                return ResourceManager.GetString("SuccessCategoryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория &quot;{0}&quot; успешно переименована в &quot;{1}&quot;!.
        /// </summary>
        public static string SuccessCategoryRenamed {
            get {
                return ResourceManager.GetString("SuccessCategoryRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория &quot;{0}&quot; успешно переименована в &quot;{1}&quot;!.
        /// </summary>
        public static string SuccessCategoryUpdated {
            get {
                return ResourceManager.GetString("SuccessCategoryUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар успешно добавлен!.
        /// </summary>
        public static string SuccessProductAdded {
            get {
                return ResourceManager.GetString("SuccessProductAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар добавлен в список отгрузки.
        /// </summary>
        public static string SuccessProductAddedToList {
            get {
                return ResourceManager.GetString("SuccessProductAddedToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар успешно удален!.
        /// </summary>
        public static string SuccessProductDeleted {
            get {
                return ResourceManager.GetString("SuccessProductDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар успешно обновлен!.
        /// </summary>
        public static string SuccessProductUpdated {
            get {
                return ResourceManager.GetString("SuccessProductUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация успешна! Добро пожаловать, {0}!.
        /// </summary>
        public static string SuccessRegistration {
            get {
                return ResourceManager.GetString("SuccessRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация успешна!
        ///
        ///Логин: {0}
        ///ФИО: {1}
        ///
        ///Теперь вы можете войти в систему..
        /// </summary>
        public static string SuccessRegistrationWithDetails {
            get {
                return ResourceManager.GetString("SuccessRegistrationWithDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отгрузка успешно оформлена!.
        /// </summary>
        public static string SuccessShipmentCreated {
            get {
                return ResourceManager.GetString("SuccessShipmentCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отгрузка успешно оформлена!
        ///
        ///Получатель: {0}
        ///Количество позиций: {1}
        ///Общая сумма: {2:C2}.
        /// </summary>
        public static string SuccessShipmentCreatedWithDetails {
            get {
                return ResourceManager.GetString("SuccessShipmentCreatedWithDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Действие запрещено.
        /// </summary>
        public static string TitleActionForbidden {
            get {
                return ResourceManager.GetString("TitleActionForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение.
        /// </summary>
        public static string TitleConfirmation {
            get {
                return ResourceManager.GetString("TitleConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение удаления.
        /// </summary>
        public static string TitleDeleteConfirmation {
            get {
                return ResourceManager.GetString("TitleDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        public static string TitleInformation {
            get {
                return ResourceManager.GetString("TitleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар уже в списке.
        /// </summary>
        public static string TitleProductAlreadyInList {
            get {
                return ResourceManager.GetString("TitleProductAlreadyInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение удаления.
        /// </summary>
        public static string TitleRemoveConfirmation {
            get {
                return ResourceManager.GetString("TitleRemoveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успех.
        /// </summary>
        public static string TitleSuccess {
            get {
                return ResourceManager.GetString("TitleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание.
        /// </summary>
        public static string TitleWarning {
            get {
                return ResourceManager.GetString("TitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите единицу измерения.
        /// </summary>
        public static string UnitSelectWatermark {
            get {
                return ResourceManager.GetString("UnitSelectWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найдено {0} отгрузок, но ни одна не содержит позиций!.
        /// </summary>
        public static string WarningShipmentsWithoutItems {
            get {
                return ResourceManager.GetString("WarningShipmentsWithoutItems", resourceCulture);
            }
        }
    }
}
