//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomechanicsProject.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutomechanicsProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя.
        /// </summary>
        public static string AuthLoginWatermark {
            get {
                return ResourceManager.GetString("AuthLoginWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите пароль.
        /// </summary>
        public static string AuthPasswordWatermark {
            get {
                return ResourceManager.GetString("AuthPasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Партия_{0:yyyyMM}.
        /// </summary>
        public static string BatchNumberFormat {
            get {
                return ResourceManager.GetString("BatchNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердить поставку.
        /// </summary>
        public static string ButtonConfirmSupply {
            get {
                return ResourceManager.GetString("ButtonConfirmSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название.
        /// </summary>
        public static string CategoryAddWatermark {
            get {
                return ResourceManager.GetString("CategoryAddWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} (товаров: {1}).
        /// </summary>
        public static string CategoryDisplayFormat_WithCount {
            get {
                return ResourceManager.GetString("CategoryDisplayFormat_WithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} (товаров: {1}).
        /// </summary>
        public static string CategoryItemFormat {
            get {
                return ResourceManager.GetString("CategoryItemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Без категории.
        /// </summary>
        public static string CategoryNone {
            get {
                return ResourceManager.GetString("CategoryNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите категорию.
        /// </summary>
        public static string CategorySelectWatermark {
            get {
                return ResourceManager.GetString("CategorySelectWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Артикул.
        /// </summary>
        public static string ColumnArticle {
            get {
                return ResourceManager.GetString("ColumnArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остаток.
        /// </summary>
        public static string ColumnBalance {
            get {
                return ResourceManager.GetString("ColumnBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория.
        /// </summary>
        public static string ColumnCategory {
            get {
                return ResourceManager.GetString("ColumnCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Срок годности.
        /// </summary>
        public static string ColumnExpiryDate {
            get {
                return ResourceManager.GetString("ColumnExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование.
        /// </summary>
        public static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена.
        /// </summary>
        public static string ColumnPrice {
            get {
                return ResourceManager.GetString("ColumnPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена закупки.
        /// </summary>
        public static string ColumnPurchasePrice {
            get {
                return ResourceManager.GetString("ColumnPurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена закупки ({0}).
        /// </summary>
        public static string ColumnPurchasePriceFormat {
            get {
                return ResourceManager.GetString("ColumnPurchasePriceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ед. изм..
        /// </summary>
        public static string ColumnUnit {
            get {
                return ResourceManager.GetString("ColumnUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} - {1} (остаток: {2} шт.).
        /// </summary>
        public static string ComboItemFormat {
            get {
                return ResourceManager.GetString("ComboItemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите отменить добавление товара?
        ///
        ///Все введенные данные будут потеряны..
        /// </summary>
        public static string ConfirmCancelAddProduct {
            get {
                return ResourceManager.GetString("ConfirmCancelAddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите отменить удаление?.
        /// </summary>
        public static string ConfirmCancelDelete {
            get {
                return ResourceManager.GetString("ConfirmCancelDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас есть несохраненные изменения.
        ///
        ///Вы действительно хотите отменить редактирование?.
        /// </summary>
        public static string ConfirmCancelEdit {
            get {
                return ResourceManager.GetString("ConfirmCancelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас есть несохраненные изменения.
        ///
        ///Вы действительно хотите отменить редактирование?.
        /// </summary>
        public static string ConfirmCancelEditWithDetails {
            get {
                return ResourceManager.GetString("ConfirmCancelEditWithDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас есть добавленные товары в списке отгрузки.
        ///
        ///Вы действительно хотите отменить создание отгрузки?.
        /// </summary>
        public static string ConfirmCancelShipment {
            get {
                return ResourceManager.GetString("ConfirmCancelShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить поставку? Все данные будут потеряны..
        /// </summary>
        public static string ConfirmCancelSupply {
            get {
                return ResourceManager.GetString("ConfirmCancelSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить категорию &quot;{0}&quot;?.
        /// </summary>
        public static string ConfirmDeleteCategory {
            get {
                return ResourceManager.GetString("ConfirmDeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В категории &quot;{0}&quot; находится {1} товаров.
        ///
        ///Вы уверены, что хотите удалить категорию и все товары в ней?
        ///Это действие нельзя отменить..
        /// </summary>
        public static string ConfirmDeleteCategoryWithProducts {
            get {
                return ResourceManager.GetString("ConfirmDeleteCategoryWithProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить товар?
        ///
        ///Артикул: {0}
        ///Название: {1}
        ///Категория: {2}
        ///Цена: {3:F2}
        ///Остаток: {4} {5}
        ///
        ///Это действие нельзя отменить!.
        /// </summary>
        public static string ConfirmDeleteProduct {
            get {
                return ResourceManager.GetString("ConfirmDeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить товар &quot;{0} - {1}&quot; из списка поставки?.
        /// </summary>
        public static string ConfirmDeleteSupplyItem {
            get {
                return ResourceManager.GetString("ConfirmDeleteSupplyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить товар &quot;{0}&quot; из списка отгрузки?.
        /// </summary>
        public static string ConfirmRemoveShipmentItem {
            get {
                return ResourceManager.GetString("ConfirmRemoveShipmentItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердить отгрузку?
        ///
        ///Получатель: {0}
        ///Количество позиций: {1}
        ///Общая сумма: {2:C2}.
        /// </summary>
        public static string ConfirmShipment {
            get {
                return ResourceManager.GetString("ConfirmShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердить поставку?
        ///Общая сумма: {0}.
        /// </summary>
        public static string ConfirmSupplyFormat {
            get {
                return ResourceManager.GetString("ConfirmSupplyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Белорусский рубль.
        /// </summary>
        public static string CurrencyBYN {
            get {
                return ResourceManager.GetString("CurrencyBYN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Валюта изменена с {0} на {1}
        ///Курс: 1 RUB = {2:F4} {3} 
        ///
        ///Все цены будут пересчитаны в {4}.
        ///Продолжить?.
        /// </summary>
        public static string CurrencyChangeConfirm {
            get {
                return ResourceManager.GetString("CurrencyChangeConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение валюты.
        /// </summary>
        public static string CurrencyChangeTitle {
            get {
                return ResourceManager.GetString("CurrencyChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Китайский юань.
        /// </summary>
        public static string CurrencyCNY {
            get {
                return ResourceManager.GetString("CurrencyCNY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Евро.
        /// </summary>
        public static string CurrencyEUR {
            get {
                return ResourceManager.GetString("CurrencyEUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0:N2} руб..
        /// </summary>
        public static string CurrencyFormat_Rub {
            get {
                return ResourceManager.GetString("CurrencyFormat_Rub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Британский фунт.
        /// </summary>
        public static string CurrencyGBP {
            get {
                return ResourceManager.GetString("CurrencyGBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Японская иена.
        /// </summary>
        public static string CurrencyJPY {
            get {
                return ResourceManager.GetString("CurrencyJPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Казахстанский тенге.
        /// </summary>
        public static string CurrencyKZT {
            get {
                return ResourceManager.GetString("CurrencyKZT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Российский рубль.
        /// </summary>
        public static string CurrencyRUB {
            get {
                return ResourceManager.GetString("CurrencyRUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доллар США.
        /// </summary>
        public static string CurrencyUSD {
            get {
                return ResourceManager.GetString("CurrencyUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохраняю кэш в: {0}.
        /// </summary>
        public static string DebugSavingCache {
            get {
                return ResourceManager.GetString("DebugSavingCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите артикул товара.
        /// </summary>
        public static string DeleteArticleWatermark {
            get {
                return ResourceManager.GetString("DeleteArticleWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Артикул.
        /// </summary>
        public static string EditArticleWatermark {
            get {
                return ResourceManager.GetString("EditArticleWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название.
        /// </summary>
        public static string EditCategoryWatermark {
            get {
                return ResourceManager.GetString("EditCategoryWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        public static string EditNameWatermark {
            get {
                return ResourceManager.GetString("EditNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена.
        /// </summary>
        public static string EditPriceWatermark {
            get {
                return ResourceManager.GetString("EditPriceWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось добавить категорию. Попробуйте позже..
        /// </summary>
        public static string ErrorAddCategory {
            get {
                return ResourceManager.GetString("ErrorAddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при добавлении товара.
        /// </summary>
        public static string ErrorAddProduct {
            get {
                return ResourceManager.GetString("ErrorAddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при входе в систему.
        /// </summary>
        public static string ErrorAuthFailed {
            get {
                return ResourceManager.GetString("ErrorAuthFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный логин или пароль!.
        /// </summary>
        public static string ErrorAuthInvalid {
            get {
                return ResourceManager.GetString("ErrorAuthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при автоматическом списании просроченных товаров.к..
        /// </summary>
        public static string ErrorAutoWriteOff {
            get {
                return ResourceManager.GetString("ErrorAutoWriteOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно удалить категорию, так как некоторые товары используются в отгрузках.
        ///Сначала удалите связанные отгрузки..
        /// </summary>
        public static string ErrorCannotDeleteCategoryWithShipments {
            get {
                return ResourceManager.GetString("ErrorCannotDeleteCategoryWithShipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория с таким названием уже существует!.
        /// </summary>
        public static string ErrorCategoryExists {
            get {
                return ResourceManager.GetString("ErrorCategoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория не найдена в базе данных!.
        /// </summary>
        public static string ErrorCategoryNotFound {
            get {
                return ResourceManager.GetString("ErrorCategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердите пароль.
        /// </summary>
        public static string ErrorConfirmPassword {
            get {
                return ResourceManager.GetString("ErrorConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось оформить отгрузку..
        /// </summary>
        public static string ErrorCreateShipment {
            get {
                return ResourceManager.GetString("ErrorCreateShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нельзя изменить валюту после добавления позиций в поставку..
        /// </summary>
        public static string ErrorCurrencyFixed {
            get {
                return ResourceManager.GetString("ErrorCurrencyFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Критическая ошибка при загрузке курсов валют.
        /// </summary>
        public static string ErrorCurrencyRatesLoad {
            get {
                return ResourceManager.GetString("ErrorCurrencyRatesLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось удалить категорию. Попробуйте позже..
        /// </summary>
        public static string ErrorDeleteCategory {
            get {
                return ResourceManager.GetString("ErrorDeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось удалить товар. Попробуйте позже..
        /// </summary>
        public static string ErrorDeleteProduct {
            get {
                return ResourceManager.GetString("ErrorDeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось отредактировать категорию. Попробуйте позже..
        /// </summary>
        public static string ErrorEditCategory {
            get {
                return ResourceManager.GetString("ErrorEditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при редактировании товара.
        /// </summary>
        public static string ErrorEditProduct {
            get {
                return ResourceManager.GetString("ErrorEditProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите артикул товара!.
        /// </summary>
        public static string ErrorEnterArticle {
            get {
                return ResourceManager.GetString("ErrorEnterArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите корректную цену!.
        /// </summary>
        public static string ErrorEnterCorrectPrice {
            get {
                return ResourceManager.GetString("ErrorEnterCorrectPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите корректное количество (целое положительное число)!.
        /// </summary>
        public static string ErrorEnterCorrectQuantity {
            get {
                return ResourceManager.GetString("ErrorEnterCorrectQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите логин.
        /// </summary>
        public static string ErrorEnterLogin {
            get {
                return ResourceManager.GetString("ErrorEnterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя.
        /// </summary>
        public static string ErrorEnterName {
            get {
                return ResourceManager.GetString("ErrorEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите пароль.
        /// </summary>
        public static string ErrorEnterPassword {
            get {
                return ResourceManager.GetString("ErrorEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите фамилию.
        /// </summary>
        public static string ErrorEnterSurname {
            get {
                return ResourceManager.GetString("ErrorEnterSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите корректную цену закупки!.
        /// </summary>
        public static string ErrorEnterValidPrice {
            get {
                return ResourceManager.GetString("ErrorEnterValidPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите корректное количество товара!.
        /// </summary>
        public static string ErrorEnterValidQuantity {
            get {
                return ResourceManager.GetString("ErrorEnterValidQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Срок годности в поставке не может превышать срок годности товара ({0}).
        /// </summary>
        public static string ErrorExpiryDateExceedsProduct {
            get {
                return ResourceManager.GetString("ErrorExpiryDateExceedsProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Срок годности не может быть в прошлом.
        /// </summary>
        public static string ErrorExpiryDateRequired {
            get {
                return ResourceManager.GetString("ErrorExpiryDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при экспорте данных..
        /// </summary>
        public static string ErrorExportToCsvWithMessage {
            get {
                return ResourceManager.GetString("ErrorExportToCsvWithMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название категории!.
        /// </summary>
        public static string ErrorFillCategory {
            get {
                return ResourceManager.GetString("ErrorFillCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заполните все обязательные поля!.
        /// </summary>
        public static string ErrorFillFields {
            get {
                return ResourceManager.GetString("ErrorFillFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, исправьте ошибки в форме.
        ///Поля, выделенные розовым, заполнены неверно..
        /// </summary>
        public static string ErrorFixFormErrors {
            get {
                return ResourceManager.GetString("ErrorFixFormErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при отображении таблицы. Некоторые колонки могут быть отображены некорректно..
        /// </summary>
        public static string ErrorFormatColumnsMessage {
            get {
                return ResourceManager.GetString("ErrorFormatColumnsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка. Попробуйте позже..
        /// </summary>
        public static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при подсветке строки.
        /// </summary>
        public static string ErrorHighlightRow {
            get {
                return ResourceManager.GetString("ErrorHighlightRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при импорте данных. Операция прервана. Подробности записаны в журнал ошибок..
        /// </summary>
        public static string ErrorImportFailed {
            get {
                return ResourceManager.GetString("ErrorImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл не содержит данных для импорта!.
        /// </summary>
        public static string ErrorImportNoData {
            get {
                return ResourceManager.GetString("ErrorImportNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найдено в каталоге.
        /// </summary>
        public static string ErrorImportNotFound {
            get {
                return ResourceManager.GetString("ErrorImportNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недостаточно товара на складе!
        ///Доступно: {0} {1}.
        /// </summary>
        public static string ErrorInsufficientStockWithDetails {
            get {
                return ResourceManager.GetString("ErrorInsufficientStockWithDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчество должно содержать только русские буквы, дефис и пробел..
        /// </summary>
        public static string ErrorInvalidLastname {
            get {
                return ResourceManager.GetString("ErrorInvalidLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин может содержать только английские буквы, цифры и подчеркивание..
        /// </summary>
        public static string ErrorInvalidLogin {
            get {
                return ResourceManager.GetString("ErrorInvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя должно содержать только русские буквы, дефис и пробел..
        /// </summary>
        public static string ErrorInvalidName {
            get {
                return ResourceManager.GetString("ErrorInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль должен содержать минимум 6 символов, хотя бы одну цифру и одну букву..
        /// </summary>
        public static string ErrorInvalidPassword {
            get {
                return ResourceManager.GetString("ErrorInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия должна содержать только русские буквы, дефис и пробел..
        /// </summary>
        public static string ErrorInvalidSurname {
            get {
                return ResourceManager.GetString("ErrorInvalidSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчество должно быть от 2 до 100 символов..
        /// </summary>
        public static string ErrorLastnameLength {
            get {
                return ResourceManager.GetString("ErrorLastnameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось загрузить категории.
        /// </summary>
        public static string ErrorLoadCategories {
            get {
                return ResourceManager.GetString("ErrorLoadCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось загрузить товар.
        /// </summary>
        public static string ErrorLoadProduct {
            get {
                return ResourceManager.GetString("ErrorLoadProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось загрузить данные товара.
        /// </summary>
        public static string ErrorLoadProductData {
            get {
                return ResourceManager.GetString("ErrorLoadProductData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось загрузить товары.
        /// </summary>
        public static string ErrorLoadProducts {
            get {
                return ResourceManager.GetString("ErrorLoadProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось загрузить список товаров. Попробуйте позже..
        /// </summary>
        public static string ErrorLoadProductsList {
            get {
                return ResourceManager.GetString("ErrorLoadProductsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось загрузить список получателей.
        /// </summary>
        public static string ErrorLoadRecipients {
            get {
                return ResourceManager.GetString("ErrorLoadRecipients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при загрузке отчета.
        /// </summary>
        public static string ErrorLoadReportFormat {
            get {
                return ResourceManager.GetString("ErrorLoadReportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось загрузить историю отгрузок..
        /// </summary>
        public static string ErrorLoadShipmentHistory {
            get {
                return ResourceManager.GetString("ErrorLoadShipmentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при загрузке поставщиков.
        /// </summary>
        public static string ErrorLoadSuppliers {
            get {
                return ResourceManager.GetString("ErrorLoadSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось загрузить список единиц измерения.
        /// </summary>
        public static string ErrorLoadUnits {
            get {
                return ResourceManager.GetString("ErrorLoadUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин должен быть от 3 до 20 символов..
        /// </summary>
        public static string ErrorLoginLength {
            get {
                return ResourceManager.GetString("ErrorLoginLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при выходе из системы.
        /// </summary>
        public static string ErrorLogout {
            get {
                return ResourceManager.GetString("ErrorLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя должно быть от 2 до 100 символов..
        /// </summary>
        public static string ErrorNameLength {
            get {
                return ResourceManager.GetString("ErrorNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас нет доступа к системе! Обратитесь к администратору..
        /// </summary>
        public static string ErrorNoAccess {
            get {
                return ResourceManager.GetString("ErrorNoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет данных для экспорта.
        /// </summary>
        public static string ErrorNoDataToExport {
            get {
                return ResourceManager.GetString("ErrorNoDataToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У выбранного товара нет срока годности. Поле даты должно быть пустым..
        /// </summary>
        public static string ErrorNoExpiryDateAllowed {
            get {
                return ResourceManager.GetString("ErrorNoExpiryDateAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавьте товары в список отгрузки!.
        /// </summary>
        public static string ErrorNoItemsInShipment {
            get {
                return ResourceManager.GetString("ErrorNoItemsInShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавьте хотя бы одну позицию!.
        /// </summary>
        public static string ErrorNoPositions {
            get {
                return ResourceManager.GetString("ErrorNoPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В базе данных нет товаров! Добавьте товары через каталог..
        /// </summary>
        public static string ErrorNoProducts {
            get {
                return ResourceManager.GetString("ErrorNoProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В базе данных нет поставщиков! Добавьте поставщиков..
        /// </summary>
        public static string ErrorNoSuppliers {
            get {
                return ResourceManager.GetString("ErrorNoSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось открыть форму добавления категории.
        /// </summary>
        public static string ErrorOpenAddCategoryForm {
            get {
                return ResourceManager.GetString("ErrorOpenAddCategoryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось открыть форму добавления товара.
        /// </summary>
        public static string ErrorOpenAddProductForm {
            get {
                return ResourceManager.GetString("ErrorOpenAddProductForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при открытии формы выбора валюты.
        /// </summary>
        public static string ErrorOpenCurrencyForm {
            get {
                return ResourceManager.GetString("ErrorOpenCurrencyForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось удалить категорию.
        /// </summary>
        public static string ErrorOpenDeleteCategoryForm {
            get {
                return ResourceManager.GetString("ErrorOpenDeleteCategoryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось открыть форму редактирования категории.
        /// </summary>
        public static string ErrorOpenEditCategoryForm {
            get {
                return ResourceManager.GetString("ErrorOpenEditCategoryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось открыть историю.
        /// </summary>
        public static string ErrorOpenHistory {
            get {
                return ResourceManager.GetString("ErrorOpenHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось открыть форму отгрузки.
        /// </summary>
        public static string ErrorOpenShipmentForm {
            get {
                return ResourceManager.GetString("ErrorOpenShipmentForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароли не совпадают!.
        /// </summary>
        public static string ErrorPasswordMismatch {
            get {
                return ResourceManager.GetString("ErrorPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно удалить товар &quot;{0}&quot;, так как он используется в {1} отгрузках..
        /// </summary>
        public static string ErrorProductInShipments {
            get {
                return ResourceManager.GetString("ErrorProductInShipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар с артикулом &quot;{0}&quot; не найден!.
        /// </summary>
        public static string ErrorProductNotFound {
            get {
                return ResourceManager.GetString("ErrorProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар не найден!.
        /// </summary>
        public static string ErrorProductNotFoundGeneric {
            get {
                return ResourceManager.GetString("ErrorProductNotFoundGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при регистрации. Попробуйте позже..
        /// </summary>
        public static string ErrorRegistration {
            get {
                return ResourceManager.GetString("ErrorRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка: роль &apos;Кладовщик&apos; не найдена!
        ///Обратитесь к администратору..
        /// </summary>
        public static string ErrorRoleNotFound {
            get {
                return ResourceManager.GetString("ErrorRoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите категорию!.
        /// </summary>
        public static string ErrorSelectCategory {
            get {
                return ResourceManager.GetString("ErrorSelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите категорию для удаления!.
        /// </summary>
        public static string ErrorSelectCategoryForDelete {
            get {
                return ResourceManager.GetString("ErrorSelectCategoryForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите товар из списка!.
        /// </summary>
        public static string ErrorSelectProduct {
            get {
                return ResourceManager.GetString("ErrorSelectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите получателя из списка!.
        /// </summary>
        public static string ErrorSelectRecipient {
            get {
                return ResourceManager.GetString("ErrorSelectRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, выберите поставщика!.
        /// </summary>
        public static string ErrorSelectSupplier {
            get {
                return ResourceManager.GetString("ErrorSelectSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите единицу измерения!.
        /// </summary>
        public static string ErrorSelectUnit {
            get {
                return ResourceManager.GetString("ErrorSelectUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при подтверждении поставки..
        /// </summary>
        public static string ErrorSupplyFailed {
            get {
                return ResourceManager.GetString("ErrorSupplyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия должна быть от 2 до 100 символов..
        /// </summary>
        public static string ErrorSurnameLength {
            get {
                return ResourceManager.GetString("ErrorSurnameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось обновить товар. Попробуйте позже..
        /// </summary>
        public static string ErrorUpdateProduct {
            get {
                return ResourceManager.GetString("ErrorUpdateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь с таким логином уже существует!.
        /// </summary>
        public static string ErrorUserExists {
            get {
                return ResourceManager.GetString("ErrorUserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка: пользователь не авторизован!.
        /// </summary>
        public static string ErrorUserNotAuthorized {
            get {
                return ResourceManager.GetString("ErrorUserNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка..
        /// </summary>
        public static string ErrorWithDetails {
            get {
                return ResourceManager.GetString("ErrorWithDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Срок: {0:dd.MM.yyyy} (остаток: {1}).
        /// </summary>
        public static string ExpiryDisplayFormat_WithBalance {
            get {
                return ResourceManager.GetString("ExpiryDisplayFormat_WithBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на yyyyMMdd_HHmmss.
        /// </summary>
        public static string FileNameDateFormat {
            get {
                return ResourceManager.GetString("FileNameDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Артикул.
        /// </summary>
        public static string History_Article {
            get {
                return ResourceManager.GetString("History_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата.
        /// </summary>
        public static string History_Date {
            get {
                return ResourceManager.GetString("History_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        public static string History_Name {
            get {
                return ResourceManager.GetString("History_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на №.
        /// </summary>
        public static string History_Number {
            get {
                return ResourceManager.GetString("History_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена.
        /// </summary>
        public static string History_Price {
            get {
                return ResourceManager.GetString("History_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прибыль.
        /// </summary>
        public static string History_Profit {
            get {
                return ResourceManager.GetString("History_Profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество.
        /// </summary>
        public static string History_Quantity {
            get {
                return ResourceManager.GetString("History_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получатель.
        /// </summary>
        public static string History_Recipient {
            get {
                return ResourceManager.GetString("History_Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кладовщик.
        /// </summary>
        public static string History_Storekeeper {
            get {
                return ResourceManager.GetString("History_Storekeeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма.
        /// </summary>
        public static string History_Total {
            get {
                return ResourceManager.GetString("History_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Импорт данных поставки из JSON файла.
        /// </summary>
        public static string ImportSupplyTitle {
            get {
                return ResourceManager.GetString("ImportSupplyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название категории не изменилось.
        /// </summary>
        public static string InfoCategoryNameNotChanged {
            get {
                return ResourceManager.GetString("InfoCategoryNameNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Курсы валют успешно загружены.
        /// </summary>
        public static string InfoCurrencyRatesLoaded {
            get {
                return ResourceManager.GetString("InfoCurrencyRatesLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задайте корректно период.
        /// </summary>
        public static string InfoHistoryEmpty {
            get {
                return ResourceManager.GetString("InfoHistoryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет данных для истории.
        /// </summary>
        public static string InfoNoDataForPeriod {
            get {
                return ResourceManager.GetString("InfoNoDataForPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет позиций для отображения.
        /// </summary>
        public static string InfoNoPositionsToDisplay {
            get {
                return ResourceManager.GetString("InfoNoPositionsToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет товаров в наличии для отгрузки!.
        /// </summary>
        public static string InfoNoProductsForShipment {
            get {
                return ResourceManager.GetString("InfoNoProductsForShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет доступных получателей!
        ///Обратитесь к администратору для добавления компаний..
        /// </summary>
        public static string InfoNoRecipientsAvailable {
            get {
                return ResourceManager.GetString("InfoNoRecipientsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Используются сохранённые курсы валют (интернет недоступен).
        /// </summary>
        public static string InfoUsingCachedCurrencies {
            get {
                return ResourceManager.GetString("InfoUsingCachedCurrencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на JSON files (*.json)|*.json|All files (*.*)|*.*.
        /// </summary>
        public static string JsonFileFilter {
            get {
                return ResourceManager.GetString("JsonFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка курсов валют....
        /// </summary>
        public static string LoadingCurrencies {
            get {
                return ResourceManager.GetString("LoadingCurrencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Н/Д.
        /// </summary>
        public static string ND {
            get {
                return ResourceManager.GetString("ND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет доступных категорий для удаления.
        /// </summary>
        public static string NoCategoriesForDelete {
            get {
                return ResourceManager.GetString("NoCategoriesForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет доступных валют.
        /// </summary>
        public static string NoCurrenciesAvailable {
            get {
                return ResourceManager.GetString("NoCurrenciesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет срока годности.
        /// </summary>
        public static string NoExpiryDateWatermark {
            get {
                return ResourceManager.GetString("NoExpiryDateWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Без срока (остаток: {0}).
        /// </summary>
        public static string NoExpiryDisplayFormat {
            get {
                return ResourceManager.GetString("NoExpiryDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не указан.
        /// </summary>
        public static string NotListed {
            get {
                return ResourceManager.GetString("NotListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, выберите валюту.
        /// </summary>
        public static string PleaseSelectCurrency {
            get {
                return ResourceManager.GetString("PleaseSelectCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар &quot;{0}&quot; уже добавлен в список.
        ///Текущее количество: {1} {2}
        ///
        ///Заменить количество новым значением?.
        /// </summary>
        public static string ProductAlreadyInList {
            get {
                return ResourceManager.GetString("ProductAlreadyInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите артикул.
        /// </summary>
        public static string ProductArticleWatermark {
            get {
                return ResourceManager.GetString("ProductArticleWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} - {1} (остаток: {2} {3}).
        /// </summary>
        public static string ProductDisplayFormat_WithBalance {
            get {
                return ResourceManager.GetString("ProductDisplayFormat_WithBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название.
        /// </summary>
        public static string ProductNameWatermark {
            get {
                return ResourceManager.GetString("ProductNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите цену.
        /// </summary>
        public static string ProductPriceWatermark {
            get {
                return ResourceManager.GetString("ProductPriceWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторите пароль.
        /// </summary>
        public static string RegConfirmPasswordWatermark {
            get {
                return ResourceManager.GetString("RegConfirmPasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите отчество.
        /// </summary>
        public static string RegLastnameWatermark {
            get {
                return ResourceManager.GetString("RegLastnameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите логин.
        /// </summary>
        public static string RegLoginWatermark {
            get {
                return ResourceManager.GetString("RegLoginWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя.
        /// </summary>
        public static string RegNameWatermark {
            get {
                return ResourceManager.GetString("RegNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите пароль.
        /// </summary>
        public static string RegPasswordWatermark {
            get {
                return ResourceManager.GetString("RegPasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите фамилию.
        /// </summary>
        public static string RegSurnameWatermark {
            get {
                return ResourceManager.GetString("RegSurnameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Артикул.
        /// </summary>
        public static string Report_Article {
            get {
                return ResourceManager.GetString("Report_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата.
        /// </summary>
        public static string Report_Date {
            get {
                return ResourceManager.GetString("Report_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        public static string Report_Name {
            get {
                return ResourceManager.GetString("Report_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена.
        /// </summary>
        public static string Report_Price {
            get {
                return ResourceManager.GetString("Report_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прибыль.
        /// </summary>
        public static string Report_Profit {
            get {
                return ResourceManager.GetString("Report_Profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество.
        /// </summary>
        public static string Report_Quantity {
            get {
                return ResourceManager.GetString("Report_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получатель.
        /// </summary>
        public static string Report_Recipient {
            get {
                return ResourceManager.GetString("Report_Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кладовщик.
        /// </summary>
        public static string Report_Storekeeper {
            get {
                return ResourceManager.GetString("Report_Storekeeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма.
        /// </summary>
        public static string Report_Total {
            get {
                return ResourceManager.GetString("Report_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Российский рубль.
        /// </summary>
        public static string RussianRuble {
            get {
                return ResourceManager.GetString("RussianRuble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить CSV файл.
        /// </summary>
        public static string SaveCsvFileTitle {
            get {
                return ResourceManager.GetString("SaveCsvFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на csv.
        /// </summary>
        public static string SaveFileDefaultExt_CSV {
            get {
                return ResourceManager.GetString("SaveFileDefaultExt_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчет_{0}.
        /// </summary>
        public static string SaveFileFileNameTemplate_Report {
            get {
                return ResourceManager.GetString("SaveFileFileNameTemplate_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CSV файлы (*.csv)|*.csv|Все файлы (*.*)|*.*.
        /// </summary>
        public static string SaveFileFilter_CSV {
            get {
                return ResourceManager.GetString("SaveFileFilter_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите валюту закупки.
        /// </summary>
        public static string SCurrencyWatermark {
            get {
                return ResourceManager.GetString("SCurrencyWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск:.
        /// </summary>
        public static string SearchWatermark {
            get {
                return ResourceManager.GetString("SearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите категорию для удаления.
        /// </summary>
        public static string SelectCategoryForDelete {
            get {
                return ResourceManager.GetString("SelectCategoryForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите категорию для редактирования.
        /// </summary>
        public static string SelectCategoryForEdit {
            get {
                return ResourceManager.GetString("SelectCategoryForEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите товар для удаления.
        /// </summary>
        public static string SelectProductForDelete {
            get {
                return ResourceManager.GetString("SelectProductForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите товар для редактирования.
        /// </summary>
        public static string SelectProductForEdit {
            get {
                return ResourceManager.GetString("SelectProductForEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите срок годности.
        /// </summary>
        public static string ShipmentExpiryDateWatermark {
            get {
                return ResourceManager.GetString("ShipmentExpiryDateWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Формирование отгрузки - Общая сумма: {0:F2}, Прибыль: {1:F2}.
        /// </summary>
        public static string ShipmentForm_TitleFormat {
            get {
                return ResourceManager.GetString("ShipmentForm_TitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на История отгрузок - Отгружено: {0} ед. | Списано: {1} ед. | Сумма: {2:C2} | Прибыль: {3:C2} | Убыток: {4:C2}.
        /// </summary>
        public static string ShipmentHistoryTitle {
            get {
                return ResourceManager.GetString("ShipmentHistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите количество товара.
        /// </summary>
        public static string ShipmentQuantityWatermark {
            get {
                return ResourceManager.GetString("ShipmentQuantityWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите получателя.
        /// </summary>
        public static string ShipmentRecipientWatermark {
            get {
                return ResourceManager.GetString("ShipmentRecipientWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Брак.
        /// </summary>
        public static string ShipmentType_Defect {
            get {
                return ResourceManager.GetString("ShipmentType_Defect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отгрузка.
        /// </summary>
        public static string ShipmentType_Shipment {
            get {
                return ResourceManager.GetString("ShipmentType_Shipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поставка.
        /// </summary>
        public static string ShipmentType_Supply {
            get {
                return ResourceManager.GetString("ShipmentType_Supply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Списание.
        /// </summary>
        public static string ShipmentType_WriteOff {
            get {
                return ResourceManager.GetString("ShipmentType_WriteOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите тип отгрузки.
        /// </summary>
        public static string ShipmentTypeWatermark {
            get {
                return ResourceManager.GetString("ShipmentTypeWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите цену.
        /// </summary>
        public static string SPriceWatermark {
            get {
                return ResourceManager.GetString("SPriceWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите товар из списка.
        /// </summary>
        public static string SProductWatermark {
            get {
                return ResourceManager.GetString("SProductWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите количество товара.
        /// </summary>
        public static string SQuantityWatermark {
            get {
                return ResourceManager.GetString("SQuantityWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите поставщика.
        /// </summary>
        public static string SSupplierWatermark {
            get {
                return ResourceManager.GetString("SSupplierWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string StatusError {
            get {
                return ResourceManager.GetString("StatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранение....
        /// </summary>
        public static string StatusSaving {
            get {
                return ResourceManager.GetString("StatusSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кладовщик.
        /// </summary>
        public static string StorekeeperRoleName {
            get {
                return ResourceManager.GetString("StorekeeperRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Списано {0} просроченных товаров..
        /// </summary>
        public static string SuccessAutoWriteOffMessage {
            get {
                return ResourceManager.GetString("SuccessAutoWriteOffMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория &quot;{0}&quot; успешно добавлена!.
        /// </summary>
        public static string SuccessCategoryAdded {
            get {
                return ResourceManager.GetString("SuccessCategoryAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория &quot;{0}&quot; и все ({1}) товары в ней успешно удалены!.
        /// </summary>
        public static string SuccessCategoryAndProductsDeleted {
            get {
                return ResourceManager.GetString("SuccessCategoryAndProductsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория &quot;{0}&quot; успешно удалена!.
        /// </summary>
        public static string SuccessCategoryDeleted {
            get {
                return ResourceManager.GetString("SuccessCategoryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория &quot;{0}&quot; успешно переименована в &quot;{1}&quot;!.
        /// </summary>
        public static string SuccessCategoryRenamed {
            get {
                return ResourceManager.GetString("SuccessCategoryRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные успешно экспортированы в файл: {0}.
        /// </summary>
        public static string SuccessExportFormat {
            get {
                return ResourceManager.GetString("SuccessExportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успешно импортировано {0} товаров!.
        /// </summary>
        public static string SuccessImportFormat {
            get {
                return ResourceManager.GetString("SuccessImportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар успешно добавлен!.
        /// </summary>
        public static string SuccessProductAdded {
            get {
                return ResourceManager.GetString("SuccessProductAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар добавлен в список отгрузки.
        /// </summary>
        public static string SuccessProductAddedToList {
            get {
                return ResourceManager.GetString("SuccessProductAddedToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар успешно удален!.
        /// </summary>
        public static string SuccessProductDeleted {
            get {
                return ResourceManager.GetString("SuccessProductDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар успешно обновлен!.
        /// </summary>
        public static string SuccessProductUpdated {
            get {
                return ResourceManager.GetString("SuccessProductUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация успешна!
        ///
        ///Логин: {0}
        ///ФИО: {1}
        ///
        ///Теперь вы можете войти в систему..
        /// </summary>
        public static string SuccessRegistrationWithDetails {
            get {
                return ResourceManager.GetString("SuccessRegistrationWithDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отгрузка успешно оформлена!
        ///
        ///Получатель: {0}
        ///Количество позиций: {1}
        ///Общая сумма: {2:C2}.
        /// </summary>
        public static string SuccessShipmentCreatedWithDetails {
            get {
                return ResourceManager.GetString("SuccessShipmentCreatedWithDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поставка оформлена!
        ///
        ///Номер: {0}
        ///Дата: {1}
        ///Товаров в поставке: {2}
        ///Общая сумма: {3}.
        /// </summary>
        public static string SuccessSupplyFormat {
            get {
                return ResourceManager.GetString("SuccessSupplyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} (поставщик &apos;{1}&apos; не найден).
        /// </summary>
        public static string SupplierNotFoundFormat {
            get {
                return ResourceManager.GetString("SupplierNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оформлена.
        /// </summary>
        public static string SupplyStatusCompleted {
            get {
                return ResourceManager.GetString("SupplyStatusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автоматическое списание.
        /// </summary>
        public static string TitleAutoWriteOff {
            get {
                return ResourceManager.GetString("TitleAutoWriteOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение.
        /// </summary>
        public static string TitleConfirmation {
            get {
                return ResourceManager.GetString("TitleConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение удаления.
        /// </summary>
        public static string TitleConfirmDelete {
            get {
                return ResourceManager.GetString("TitleConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение удаления.
        /// </summary>
        public static string TitleDeleteConfirmation {
            get {
                return ResourceManager.GetString("TitleDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        public static string TitleInformation {
            get {
                return ResourceManager.GetString("TitleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар уже в списке.
        /// </summary>
        public static string TitleProductAlreadyInList {
            get {
                return ResourceManager.GetString("TitleProductAlreadyInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение удаления.
        /// </summary>
        public static string TitleRemoveConfirmation {
            get {
                return ResourceManager.GetString("TitleRemoveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успех.
        /// </summary>
        public static string TitleSuccess {
            get {
                return ResourceManager.GetString("TitleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание.
        /// </summary>
        public static string TitleWarning {
            get {
                return ResourceManager.GetString("TitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на шт.
        /// </summary>
        public static string Unit_Piece_Short {
            get {
                return ResourceManager.GetString("Unit_Piece_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите единицу измерения.
        /// </summary>
        public static string UnitSelectWatermark {
            get {
                return ResourceManager.GetString("UnitSelectWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не указан.
        /// </summary>
        public static string UnknownSupplier {
            get {
                return ResourceManager.GetString("UnknownSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки курсов валют: {0}.
        /// </summary>
        public static string WarningCurrencyRatesFailed {
            get {
                return ResourceManager.GetString("WarningCurrencyRatesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось загрузить актуальные курсы валют. Используются резервные значения..
        /// </summary>
        public static string WarningCurrencyRatesFallback {
            get {
                return ResourceManager.GetString("WarningCurrencyRatesFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задайте корректно период.
        /// </summary>
        public static string WarningNoDataForPeriod {
            get {
                return ResourceManager.GetString("WarningNoDataForPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задайте корректно период.
        /// </summary>
        public static string WarningNoHistoryForPeriod {
            get {
                return ResourceManager.GetString("WarningNoHistoryForPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У выбранного товара нет срока годности. Дата поставки не требуется..
        /// </summary>
        public static string WarningNoProductExpiryDate {
            get {
                return ResourceManager.GetString("WarningNoProductExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найдено {0} отгрузок, но ни одна не содержит позиций!.
        /// </summary>
        public static string WarningShipmentsWithoutItems {
            get {
                return ResourceManager.GetString("WarningShipmentsWithoutItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Используются сохранённые курсы валют (интернет недоступен).
        /// </summary>
        public static string WarningUsingCachedRates {
            get {
                return ResourceManager.GetString("WarningUsingCachedRates", resourceCulture);
            }
        }
    }
}
